apiVersion: v1
kind: Namespace
metadata:
  name: api-listagem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-listagem-deployment
  namespace: api-listagem
  labels:
    app: apilistagem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apilistagem
  template:
    metadata:
      labels:
        app: apilistagem
    spec:
      containers:
      - name: apilistagem
        image: lucaslearningsw/tech-api-listagem:latest
        ports:
        - containerPort: 8085
        env:
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:8085"
        - name: MSSQL_USER
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: MSSQL_USER
        - name: SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: SA_PASSWORD
        - name: MSSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: MSSQL_HOST
        - name: RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: host
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: apilistagem-service
  namespace: api-listagem
spec:
  selector:
    app: apilistagem
  ports:
    - protocol: TCP
      port: 8085      # Port exposed externally
      targetPort: 8085  # Port on the container
  type: NodePort