// <auto-generated />
using System;
using System.Collections.Generic;
using Fiap.TechChallenge.One.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.TechChallenge.One.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240718232645_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.TechChallenge.One.Domain.Contatos.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DddId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Fiap.TechChallenge.One.Domain.Contatos.Contato.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Nome", "Fiap.TechChallenge.One.Domain.Contatos.Contato.Nome#Nome", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Nome");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Telefone", "Fiap.TechChallenge.One.Domain.Contatos.Contato.Telefone#Telefone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("nvarchar(9)")
                                .HasColumnName("Telefone");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DddId");

                    b.ToTable("Contatos", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.One.Domain.Ddds.Ddd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoRegiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Codigo");

                    b.ComplexProperty<Dictionary<string, object>>("Estado", "Fiap.TechChallenge.One.Domain.Ddds.Ddd.Estado#Estado", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("DescricaoEstado");

                            b1.Property<string>("Sigla")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("SiglaEstado");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CodigoRegiao")
                        .IsUnique();

                    b.ToTable("Ddds", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.One.Domain.Contatos.Contato", b =>
                {
                    b.HasOne("Fiap.TechChallenge.One.Domain.Ddds.Ddd", "Ddd")
                        .WithMany("Contatos")
                        .HasForeignKey("DddId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ddd");
                });

            modelBuilder.Entity("Fiap.TechChallenge.One.Domain.Ddds.Ddd", b =>
                {
                    b.Navigation("Contatos");
                });
#pragma warning restore 612, 618
        }
    }
}
