version: '3.7'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlservercontainer
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SuaSenhaSegura"
      ACCEPT_EULA: "Y"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge