global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'fiap-techchallenge-api-cadastro'
    static_configs:
      - targets: ['techchallenge.api.cadastro:8080']

  - job_name: 'fiap-techchallenge-api-atualizacao'
    static_configs:
      - targets: ['techchallenge.api.atualizacao:8082']

  - job_name: 'fiap-techchallenge-api-exclusao'
    static_configs:
      - targets: ['techchallenge.api.exclusao:8083']

  - job_name: 'fiap-techchallenge-api-listagem'
    static_configs:
      - targets: ['techchallenge.api.listagem:8084']
