apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cadastro-deployment
  namespace: api-cadastro
  labels:
    app: apicadastro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicadastro
  template:
    metadata:
      labels:
        app: apicadastro
    spec:
      containers:
      - name: apicadastro
        image: lucaslearningsw/tech-api-cadastro:latest
        ports:
        - containerPort: 8080
        env:
        - name: MSSQL_USER
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: MSSQL_USER
        - name: SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: SA_PASSWORD
        - name: MSSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: MSSQL_HOST
        - name: RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: host
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: apicadastro-service
  namespace: api-cadastro
spec:
  selector:
    app: apicadastro
  ports:
    - protocol: TCP
      port: 80        # Port exposed externally
      targetPort: 8080  # Port on the container
  type: NodePort