apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp-namespace
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: lucaslearningsw/tech-fiap-atualizacao:1.0
        ports:
        - containerPort: 80  
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"  
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: password
        - name: SQL_SERVER_HOST
          value: "sqlserver-service"  # Update with your SQL Server service name
        - name: SQL_SERVER_USER
          value: "sa"  # Change to your SQL Server username if different
        - name: SQL_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: sa-password
        resources:
          requests:
            memory: "512Mi"  # Minimum memory request
            cpu: "250m"      # Minimum CPU request
          limits:
            memory: "1Gi"    # Maximum memory limit
            cpu: "500m"      # Maximum CPU limit