apiVersion: v1
kind: Namespace
metadata:
  name: api-atualizacao

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-atualizacao-deployment
  namespace: api-atualizacao
  labels:
    app: apiatualizacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiatualizacao
  template:
    metadata:
      labels:
        app: apiatualizacao
    spec:
      containers:
      - name: apiatualizacao
        image: lucaslearningsw/tech-api-atualizacao:latest
        ports:
        - containerPort: 8084
        env:
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:8084"
        - name: MSSQL_USER
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: MSSQL_USER
        - name: SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: SA_PASSWORD
        - name: MSSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: MSSQL_HOST
        - name: RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: host
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: apiatualizacao-service
  namespace: api-atualizacao
spec:
  selector:
    app: apiatualizacao
  ports:
    - protocol: TCP
      port: 8085        # Port exposed externally
      targetPort: 8084 # Port on the container
  type: NodePort