# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Develop

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Create Container
      run: |
         docker pull mcr.microsoft.com/mssql/server
         docker run -v ~/docker --name sqlserver -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=1q2w3e4r@#$" -p 1433:1433 -d mcr.microsoft.com/mssql/server
        
    - name: Restore dependencies
      run: dotnet restore Fiap.TechChallenge.One.sln
      
    - name: Build
      run: dotnet build Fiap.TechChallenge.One.sln --no-restore
      
    - name: Test
      run: dotnet test Fiap.TechChallenge.One.sln --no-build --verbosity normal
