apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserver-config
  namespace: sqlserver-namespace
  labels:
    app: sqlserver
  annotations:
    description: "SQL Server ConfigMap to store environment variables and configuration data"
data:
  ACCEPT_EULA: "Y"