apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: sqlserver-namespace
  labels:
    app: sqlserver
type: Opaque
data:
  sa-password: c3FscGFzc3dvcmQhMTIz # This is "sqlpassword!123" base64 encoded